package enums;

public enum Dimensions {

	FRAME(1366, 1000),
	INSETS(7, 29),
	GAP_BETWEEN_BORDERS(10, 10),
	GAP_BETWEEN_COMPONENTS(10, 10),
	MAP_ORIGINAL(1163, 1500),
	MAP_RATIO((FRAME.y() - 2 * GAP_BETWEEN_BORDERS.y()) / MAP_ORIGINAL.y(), (FRAME.y() - 2 * GAP_BETWEEN_BORDERS.y()) / MAP_ORIGINAL.y()),
	MAP_GAME(MAP_ORIGINAL.x() * MAP_RATIO.x(), MAP_ORIGINAL.y() * MAP_RATIO.y()),
	MOUNTAINEER_GAME(SpaceSize.SMALL.height() * Dimensions.MAP_RATIO.x() / 2, SpaceSize.SMALL.height() * Dimensions.MAP_RATIO.y() / 2),
	TENT_ORIGINAL(229, 155),
	TENT_GAME(MOUNTAINEER_GAME.x(), TENT_ORIGINAL.y() * MOUNTAINEER_GAME.x() / TENT_ORIGINAL.x()),
	ACCLIMATIZATION_INDICATOR_ORIGINAL(1654, 591),
	ACCLIMATIZATION_INDICATOR_RATIO(150 / ACCLIMATIZATION_INDICATOR_ORIGINAL.y(), 150 / ACCLIMATIZATION_INDICATOR_ORIGINAL.y()),
	ACCLIMATIZATION_INDICATOR_GAME(ACCLIMATIZATION_INDICATOR_ORIGINAL.x() * ACCLIMATIZATION_INDICATOR_RATIO.x(), ACCLIMATIZATION_INDICATOR_ORIGINAL.y() * ACCLIMATIZATION_INDICATOR_RATIO.y()),
	
	;

	private double x = -1, y = -1;

	private Dimensions(double x, double y) {
		this.x = x;
		this.y = y;
	}

	public double x() {
		return x;
	}

	public double y() {
		return y;
	}

}
